### ISSUE TITLE
Download and Copy Link links have double-backslash using using BASE_URL

### ISSUE THREAD

**Issue by michaelkrieger** [timvisee/send#163]
On the https://send.mydomain.com/ page, the "Download" and "Copy Link" links have a double-backslash, which prevents them from working. i.e.: https://send.mydomain.com:9876//download/11f2...2810/#YbL...ZNwg . Clicking either link states that "This link has expired."  Simply removing a backslash brings me to "Download files.  This file was shared...".

Naturally the double-backslash shouldn't be there.  I don't see any configuration concerns that would add it.  Tried BASE_URL both with and without a trailing backslash.

docker-compose configuration...
```
  send:
    image: registry.gitlab.com/timvisee/send:latest
    restart: always
    volumes:
      - /serverfilepath:/uploads
    environment:
      - VIRTUAL_HOST=send.mydomain.com
      - VIRTUAL_PORT=9876
      - DHPARAM_GENERATION=false
      - NODE_ENV=production
      - BASE_URL=https://send.mydomain.com:9876
      - MAX_FILE_SIZE=10737418240
      - MAX_EXPIRE_SECONDS=2592000
      - REDIS_HOST=redis
      - FILE_DIR=/uploads
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.send.entrypoints=secure'
      - 'traefik.http.routers.send.rule=Host(`send.mydomain.com`)'
      - 'traefik.http.routers.send.tls=true'
```
