### ISSUE TITLE
EACCES Error: permission denied

### ISSUE THREAD

**Issue by Fred-DTV** [timvisee/send#206]
Everything seems to be working fine but the uploads stop at about a third of the process and I receive this error:

`Timestamp=1735581676487000000 Logger=FirefoxSend Type=uncaughtException Severity=0 Pid=1 EnvVersion=2.0 Fields={"error":"Error: EACCES: permission denied, unlink '/uploads/14-5ad94595f26438cd'","stack":"\n    at Object.unlinkSync (node:fs:1718:3)\n    at WriteStream.<anonymous> (/app/server/storage/fs.js:34:12)\n    at WriteStream.emit (node:events:402:35)\n    at WriteStream.emit (node:domain:475:12)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"} `

It's running vie docker-compose and Portainer on my Synology NAS

I thought it might be a volume issue but I've tried mounting it directly in the compose and via NFS and neither is working.

Anyone has ideas what is causing this?

My docker-compose:
````
services:
  send:
    image: '${DOCKER_SEND_IMAGE}'
    restart: always
    ports:
      - '1234:1234'
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "transfer"
      tsdproxy.funnel: "true"
    volumes:
      - /volume1/Archiv/TRANSFER:/uploads
    env_file:
      - stack.env

  redis:
    image: 'redis:alpine'
    restart: always
    volumes:
      - send-redis:/data

volumes:
  uploads:
    driver: local
    driver_opts:
      type: nfs
      o: addr=2.39.2.50,rw,nolock,soft,nfsvers=4.1
      device: :/volume1/Archiv/TRANSFER
  send-redis:
  proxy-certs:
  proxy-vhost:
  proxy-html:
````

And the envs:
<img width="555" alt="Screenshot 2024-12-30 at 19 08 17" src="https://github.com/user-attachments/assets/264bfb21-ed24-460f-b060-3de4430576d1" />
