### ISSUE TITLE
All links appears as expired

### ISSUE THREAD

**Issue by Magikh42** [timvisee/send#208]
Hello, I installed send using docker compose

I can access the service and upload files but when I try to download I get an error: "This link has expired."
Maybe my I made an error when editing the compose file

compose.yaml
```
services:
  send:
    container_name: send
    image: registry.gitlab.com/timvisee/send:latest
    restart: always
    depends_on:
      - send-redis
    volumes:
      - ./uploads:/uploads
    environment:
      - VIRTUAL_HOST=send.mydomain.tld
      - VIRTUAL_PORT=3000
      - DHPARAM_GENERATION=false
      - NODE_ENV=production
      - BASE_URL=https://send.mydomain.tld
      - PORT=3000
      - REDIS_HOST=send-redis
      - FILE_DIR=/uploads
    networks:
      - immersion

  send-redis:
    container_name: send-redis
    image: redis:alpine
    restart: always
    volumes:
      - volume-send-redis:/data

volumes:
  volume-send-redis:

networks:
  immersion:
    name: immersion
    external: true
```

Caddyfile:
```
send.mydomain.tld {
	encode zstd gzip
	reverse_proxy send:3000
}

```

**Comment by Magikh42** [comment]
Here are the errors massages in the logs:

`AbortError: HSET can't be processed. The connection is already closed.`
`AbortError: HMSET can't be processed. The connection is already closed.`
`AbortError: EXPIRE can't be processed. The connection is already closed.`

**Comment by Tupiet** [comment]
Hi! First of all, thanks for mantaining this amazing service! 

Same problem here. As @Magikh42, I can upload files (they are uploaded to the `uploads` folder), but when I try to download them, I receive the error: "This link has expired ".

This is my docker-compose.yaml

```yaml
services:
  send:
    image: '${DOCKER_SEND_IMAGE}'
    restart: always
    ports:
      - '${PORT}:1234'
    volumes:
      - ./uploads:/uploads
    environment:
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PORT=1234
      - DHPARAM_GENERATION=false
      - NODE_ENV=production
      - DETECT_BASE_URL=true
      - PORT=1234
      - REDIS_HOST=redis

      # For local uploads storage
      - FILE_DIR=/uploads
  redis:
    image: 'redis:alpine'
    restart: always
    volumes:
      - send-redis:/data

volumes:
  send-redis:
```

When watching the logs (`docker logs send-send-1`), I get the same errors that @Magikh42 gets:

```text
{"Timestamp":1743954705346000000,"Logger":"FirefoxSend","Type":"send.storage.Redis:","Severity":2,"Pid":1,"EnvVersion":"2.0","Fields":{"error":"AbortError: HSET can't be processed. The connection is already closed.","stack":"\n    at handle_offline_command (/app/node_modules/redis/index.js:780:15)\n    at RedisClient.internal_send_command (/app/node_modules/redis/index.js:814:9)\n    at RedisClient.hset (/app/node_modules/redis/lib/commands.js:46:25)\n    at DB.set (/app/server/storage/index.js:54:16)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async WebSocket.<anonymous> (/app/server/routes/ws.js:92:7)"}}
{"Timestamp":1743954705347000000,"Logger":"FirefoxSend","Type":"send.storage.Redis:","Severity":2,"Pid":1,"EnvVersion":"2.0","Fields":{"error":"AbortError: HMSET can't be processed. The connection is already closed.","stack":"\n    at handle_offline_command (/app/node_modules/redis/index.js:780:15)\n    at RedisClient.internal_send_command (/app/node_modules/redis/index.js:814:9)\n    at RedisClient.hmset (/app/node_modules/redis/lib/individualCommands.js:364:17)\n    at DB.set (/app/server/storage/index.js:56:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async WebSocket.<anonymous> (/app/server/routes/ws.js:92:7)"}}
{"Timestamp":1743954705347000000,"Logger":"FirefoxSend","Type":"send.storage.Redis:","Severity":2,"Pid":1,"EnvVersion":"2.0","Fields":{"error":"AbortError: EXPIRE can't be processed. The connection is already closed.","stack":"\n    at handle_offline_command (/app/node_modules/redis/index.js:780:15)\n    at RedisClient.internal_send_command (/app/node_modules/redis/index.js:814:9)\n    at RedisClient.expire (/app/node_modules/redis/lib/commands.js:46:25)\n    at DB.set (/app/server/storage/index.js:58:16)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async WebSocket.<anonymous> (/app/server/routes/ws.js:92:7)"}}
```

Is there anything we are doing wrong? Thanks!
