### ISSUE TITLE
download problem

### ISSUE THREAD

**Issue by caglaryalcin** [timvisee/send#209]
Hi, I've just upgraded the send platform on kubernetes. I can upload files, but when I try to download from the link I get the error in the picture. 

I didn't want to use the nginx configuration, could that be the problem?

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: send-config
data:
  HOST: "10.0.0.105:31234"
  SEND_BASE_URL: "http://10.0.0.105:31234/"
  BASE_URL: "http://10.0.0.105:31234/"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: send-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /nasmount/k8s/send/redis
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: send-upload-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mypath
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: send-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: send-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: send-upload-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: send-upload-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: send
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: send
  template:
    metadata:
      labels:
        app: send
    spec:
      containers:
      - name: send
        image: registry.gitlab.com/timvisee/send:latest
        ports:
        - containerPort: 1234
        env:
        - name: VIRTUAL_HOST
          valueFrom:
            configMapKeyRef:
              name: send-config
              key: HOST
        - name: VIRTUAL_PORT
          value: "1234"
        - name: DHPARAM_GENERATION
          value: "false"
        - name: NODE_ENV
          value: production
        - name: BASE_URL
          valueFrom:
            configMapKeyRef:
              name: send-config
              key: SEND_BASE_URL
        - name: PORT
          value: "1234"
        - name: REDIS_HOST
          value: redis
        - name: MAX_FILE_SIZE
          value: "53687091200" # 50GB
        - name: DETECT_BASE_URL
          value: "true"
        volumeMounts:
        - name: send-data
          mountPath: /data
        volumeMounts:
        - name: send-upload-data
          mountPath: /uploads
      volumes:
      - name: send-upload-data
        persistentVolumeClaim:
          claimName: send-upload-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: send-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: send
  namespace: default
spec:
  selector:
    app: send
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 1234
      nodePort: 31234
  type: NodePort
```

![Image](https://github.com/user-attachments/assets/d2caba33-d3a8-48a7-88e0-2cccaba9093a)

![Image](https://github.com/user-attachments/assets/cb0ad338-ecbd-4a44-bd32-ec95dc38e03c)
