### ISSUE TITLE
`MAX_EXPIRE_SECONDS`, `MAX_DOWNLOADS`, and `MAX_FILE_SIZE` env variables don't change UI dropdowns

### ISSUE THREAD

**Issue by pirate** [timvisee/send#33]
Hi, thanks for maintaining this fork! Really appreciate it.

---

**UPDATE: I figured it out, here's a final working config to allow up to 10GB uploaded for 5yr and 250k downloads.**

```yaml
services:
  send:
    ...
    environment:
      ...
      # these update both the backend limit and the limit shown/enforced in the UI
      - MAX_FILE_SIZE=10747904000
      - MAX_FILES_PER_ARCHIVE=1024
      
      # these update the UI dropdowns and should be a CSV of bare integers (first value is used as the dropdown default)
      - EXPIRE_TIMES_SECONDS=3600,86400,604800,2592000,31536000,157680000
      - DOWNLOAD_COUNTS=1,2,5,10,15,25,50,100,1000,10000,100000,250000
      
      # these are global limits enforced by the backend and have no effect on the UI
      - DEFAULT_EXPIRE_SECONDS=157680000
      - MAX_EXPIRE_SECONDS=315360000
      - MAX_DOWNLOADS=250000
```

![image](https://user-images.githubusercontent.com/511499/118739556-bc6dc080-b817-11eb-9f9e-a25fb538ed3c.png)

---
Original ticket:
---

Changing `MAX_EXPIRE_SECONDS`, `MAX_DOWNLOADS`, and `MAX_FILE_SIZE` seems to have no effect on the UI when running with the latest Docker image, the dropdowns still only show the default maximums:

![image](https://user-images.githubusercontent.com/511499/118735384-5597d980-b80e-11eb-94f3-a81a012b430a.png)

I know the environment variables are being read, because `BASE_URL` `FILE_DIR` are being set correctly when I change them.

Here is my `docker-compose.yml` config:
```yaml
version: '3.9'

services:
  send:
    image: 'registry.gitlab.com/timvisee/send:latest'
    ports:
      - '1234:1234'
    volumes:
      - ./uploads:/uploads
    environment:
      - NODE_ENV=production
      - BASE_URL=https://send.example.com   # placeholder for my actual domain
      - PORT=1234
      - REDIS_HOST=redis
      - FILE_DIR=/uploads
      - MAX_EXPIRE_SECONDS=315360000       # 10 years
      - MAX_DOWNLOADS=200000               # 200k downloads
      - MAX_FILE_SIZE=10737418240          # 10 GB
      - ANON_MAX_EXPIRE_SECONDS=315360000
      - ANON_MAX_DOWNLOADS=20000
      - ANON_MAX_FILE_SIZE=10737418240

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - ./redis:/data
```
(based on https://github.com/timvisee/send-docker-compose/blob/master/docker-compose.yaml)

**Versions:**
- Host OS: `Ubuntu 20.04 (amd64)`
- Docker: `v20.10.6`
- Docker Compose: `v1.28.5`
- Send Image: `latest` (Digest: `9144b0f` from https://gitlab.com/timvisee/send/container_registry/1418504)

**Comment by pirate** [comment]
Based on https://github.com/timvisee/send/blob/master/server/config.js it looks like I might have to set `EXPIRE_TIMES_SECONDS` to get the UI to change?

If that's the case, should the documentation + example compose file be updated to include these extra vars that need to be set to update the UI?

(also are the `ANON_` prefixed settings still used or are those removed? if not, we should update the example config in `timvisee/send-docker-compose`)

**Comment by pirate** [comment]
I managed to increase it to 100k downloads and 365 days max, but I still cant get it to allow more than that no matter how I set the environment variables. It seems to ignore anything over those values, but I cant figure out where they're hardcoded.

This config should allow `1h, 1d, 1w, 1m, 1y, 5y`, `250k` downloads, and `10GB` limits, but the UI doesn't show anything over `100,000` and `365 Days`:
```yaml
services:
  send:
    ...
    environment:
      ...      
      
      - EXPIRE_TIMES_SECONDS="[3600, 86400, 604800, 2592000, 31536000, 157680000]"
      - DEFAULT_EXPIRE_SECONDS=157680000
      - MAX_EXPIRE_SECONDS=315360000
      - DOWNLOAD_COUNTS="[1, 2, 5, 10, 15, 25, 50, 100, 1000, 10000, 100000, 250000]"
      - MAX_DOWNLOADS=250000
      - MAX_FILES_PER_ARCHIVE=4096
      - MAX_ARCHIVES_PER_USER=4096
      - MAX_FILE_SIZE=10747904000
```

![image](https://user-images.githubusercontent.com/511499/118738482-2c2e7c00-b815-11eb-942d-46cc428cf7bc.png)

**Comment by pirate** [comment]
Ok got it working. Changing the array config options to CSV values worked.

**Here's the final working config to allow up to 10GB uploaded for 5yr and 250k downloads.**

```yaml
services:
  send:
    ...
    environment:
      ...
      - EXPIRE_TIMES_SECONDS=3600,86400,604800,2592000,31536000,157680000
      - DEFAULT_EXPIRE_SECONDS=157680000
      - MAX_EXPIRE_SECONDS=315360000
      - DOWNLOAD_COUNTS=1,2,5,10,15,25,50,100,1000,10000,100000,250000
      - MAX_DOWNLOADS=250000
      - MAX_FILE_SIZE=10747904000
```

![image](https://user-images.githubusercontent.com/511499/118739556-bc6dc080-b817-11eb-9f9e-a25fb538ed3c.png)
