### ISSUE TITLE
Cannot use own host

### ISSUE THREAD

**Issue by HenryJi529** [timvisee/send#55]
<img width="759" alt="1" src="https://user-images.githubusercontent.com/41288155/131060096-a9bee5dd-b780-42ea-8b7e-299335e51a5c.png">

I am able to access the port with curl, however, failed to upload files.

docker-compose.yml:
```
version: '3'
services:
  send:
    image: registry.gitlab.com/timvisee/send:latest
    environment: 
        DETECT_BASE_URL: 'true'
        REDIS_HOST: localhost
        BASE_URL: 'https://send.morningstar529.com'
        MAX_EXPIRE_SECONDS: 31536000
        DEFAULT_EXPIRE_SECONDS: 86400
        # size values are are in bytes, e.g. 10GB * 1024*1024*1024 = 10,747,904,000 bytes
        MAX_FILE_SIZE: 10747904000
        # array configs are set as CSV (first entry is the default for the UI dropdown)
        EXPIRE_TIMES_SECONDS: 86400,3600,86400,604800,2592000,31536000,157680000
        DOWNLOAD_COUNTS: 1,2,5,10,15,25,50,100,1000,10000,100000,250000
    container_name: morningstar_send
    tty: true
    restart: unless-stopped
    volumes:
      - /home/jeep_jipu/apps/send/uploads:/uploads
    ports:
      - "1443:1443"
```
