### ISSUE TITLE
WebSocket connection to 'wss://sub.domain.com/api/ws' failed

### ISSUE THREAD

**Issue by niterfjord** [timvisee/send#87]
Hello, I installed Send with docker compose with the following file but when I tried to upload a file, the console said WebSocket connection to 'wss://sub.domain.com/api/ws' failed.

Compose:
```
version: "3.9"

volumes:
  data:

services:
  jdf-send:
    image: registry.gitlab.com/timvisee/send:latest
    ports:
      - "9986:1443"
    volumes:
      - data:/uploads
    environment:
      - DETECT_BASE_URL=true
      - BASE_URL=https://sub.domain.com
      - REDIS_HOST=localhost
```
